fix: db tunnel in tf init

diff --git a/.github/actions/terraform-init/action.yml b/.github/actions/terraform-init/action.yml
--- a/.github/actions/terraform-init/action.yml
+++ b/.github/actions/terraform-init/action.yml
@@ -2,8 +2,7 @@ name: Terraform Actions
 
 inputs:
   aws-account-id:
-    required: false
-    default: 637192944017 # Root account
+    required: true
   aws-region:
     required: false
     default: us-east-1
@@ -28,11 +27,11 @@ runs:
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-region: ${{ inputs.aws-region }}
-        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.service-name }}__oidc
+        role-to-assume: arn:aws:iam::637192944017:role/${{ inputs.service-name }}__oidc
         role-skip-session-tagging: true
 
-    - name: Assume AWS Role in Production Account
-      if: inputs.aws-account-id != ''
+    - name: Assume AWS Role in App Account
+      if: inputs.db-tunnel-mapping != ''
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-region: us-east-1
@@ -45,20 +44,20 @@ runs:
       run: |
         SSH_CMD="ssh -v -4 -N -o StrictHostKeyChecking=no"
 
-        # $db-tunnel-mapping has form of "port1:param1:port2:param2"
-        IFS=',' read -ra MAPPING <<< "$db-tunnel-mapping"
+        # $DB_TUNNEL_MAPPING has form of "port1:param1:port2:param2"
+        IFS=',' read -ra MAPPING <<< "$DB_TUNNEL_MAPPING"
         for i in "${MAPPING[@]}"; do
-              IFS=':' read -ra PARTS <<< "$i"
-              PORT=${PARTS[0]}
-              PARAM=${i#"$PORT":}
+          IFS=':' read -ra PARTS <<< "$i"
+          PORT=${PARTS[0]}
+          PARAM=${i#"$PORT":}
 
-              URL=$(aws ssm get-parameters --names "$PARAM" --region=$aws-region --query 'Parameters[].Value' --output text)
-              if [ $? -ne 0 ]; then
-                    echo "Error getting parameter $PARAM"
-                    exit 1
-              fi
+          URL=$(aws ssm get-parameters --names "$PARAM" --region=$AWS_REGION --query 'Parameters[].Value' --output text)
+          if [ $? -ne 0 ]; then
+                echo "Error getting parameter $PARAM"
+                exit 1
+          fi
 
-              SSH_CMD="$SSH_CMD -L $PORT:$URL:5432"
+          SSH_CMD="$SSH_CMD -L $PORT:$URL:5432"
         done
 
         INSTANCE_ID=$(aws ec2 describe-instances --filter "Name=tag:Connection,Values=Bastion" --query "Reservations[].Instances[?State.Name == 'running'].InstanceId[] | [0]" --output text)
@@ -69,8 +68,8 @@ runs:
         sleep 1
       shell: bash
       env:
-        aws-region: ${{ inputs.aws-region }}
-        db-tunnel-mapping: ${{ inputs.db-tunnel-mapping }}
+        AWS_REGION: ${{ inputs.aws-region }}
+        DB_TUNNEL_MAPPING: ${{ inputs.db-tunnel-mapping }}
     
     - name: Assume AWS Role in Root Account Using OIDC
       uses: aws-actions/configure-aws-credentials@v4
