feat: migrate to pnpm FGR3-5189 (#114)

diff --git a/.github/actions/ci-node-test-e2e-lambda/action.yml b/.github/actions/ci-node-test-e2e-lambda/action.yml
--- a/.github/actions/ci-node-test-e2e-lambda/action.yml
+++ b/.github/actions/ci-node-test-e2e-lambda/action.yml
@@ -14,6 +14,10 @@ inputs:
     description: Whether to use legacy peer dependencies
     required: false
     default: false
+  pnpm-version:
+    description: pnpm version to use
+    required: false
+    default: "11.20.0"
   service-name:
     description: The service name
     required: true
@@ -25,7 +29,9 @@ runs:
       uses: actions/checkout@v6
 
     - name: Set Up Node.js
-      uses: FigurePOS/github-actions/.github/actions/node-setup@v5
+      uses: FigurePOS/github-actions/.github/actions/node-setup@v6
+      with:
+        pnpm-version: ${{ inputs.pnpm-version }}
 
     - name: Assume AWS Role in Root Account Using OIDC
       uses: aws-actions/configure-aws-credentials@v6
@@ -38,7 +44,7 @@ runs:
       uses: aws-actions/amazon-ecr-login@v2
 
     - name: Install Dependencies
-      uses: FigurePOS/github-actions/.github/actions/node-npm-install@v5
+      uses: FigurePOS/github-actions/.github/actions/node-pnpm-install@v6
       with:
         directory: ${{ inputs.directory }}
         legacy-peer-deps: ${{ inputs.npm-legacy-peer-deps }}
@@ -67,7 +73,7 @@ runs:
         fi
 
         # Run tests
-        if ! TEST_CMD="npm run ti" npm run tip; then
-          echo "::error::npm run tip failed in ${{ inputs.directory }}"
+        if ! TEST_CMD="pnpm run ti" pnpm run tip; then
+          echo "::error::pnpm run tip failed in ${{ inputs.directory }}"
           exit 1
         fi
